risoluzione problemi di indentazione nel maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -11,7 +11,7 @@ jobs:
       matrix:
         include:
           - java: 17
-            additional-maven-args: "-Pjacoco,mutation-testing,html-report " # add coveralls:report then
+            additional-maven-args: "-Pjacoco,mutation-testing,html-report"
           - java: 21
 
     steps:
@@ -31,13 +31,13 @@ jobs:
 
       - name: Build with Maven
         run: mvn clean verify ${{ matrix.additional-maven-args }}
-        working-directory: ./sessionBuilderParent  # add env: COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
+        working-directory: ./sessionBuilderParent
 
-	  - name: Upload to Coveralls (non-blocking) # temporary
-  		run: mvn coveralls:report || echo "Coveralls failed but build continues"
-		working-directory: ./sessionBuilderParent
-		env:
-      		COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
+      - name: Upload to Coveralls (non blocking)
+        run: mvn coveralls:report || echo "Coveralls failed but build continues"
+        working-directory: ./sessionBuilderParent
+        env:
+          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
 
       - name: Archive Surefire XML reports
         uses: actions/upload-artifact@v4
@@ -46,9 +46,9 @@ jobs:
           name: surefire-xml-jdk-${{ matrix.java }}
           path: '**/target/surefire-reports/'
 
-#      - name: Archive Surefire HTML report
-#        uses: actions/upload-artifact@v4
-#        if: ${{ always() }}
-#        with:
-#          name: surefire-html-jdk-${{ matrix.java }}
-#          path: '**/target/site/surefire-report.html'
+#     - name: Archive Surefire HTML report
+#       uses: actions/upload-artifact@v4
+#       if: ${{ always() }}
+#       with:
+#         name: surefire-html-jdk-${{ matrix.java }}
+#         path: '**/target/site/surefire-report.html'
